### ISSUE TITLE
Thorを使ってサブコマンド化

### ISSUE THREAD

**Issue by tdtds** [tdtds/points-scraper#2]
今の「points-hogehoge」みたいな形ではなく、「points hogehoge」のように「hogehoge」部分をpointsコマンドのサブコマンドにした方がサービス追加時の重複がなくなってよさそう。Thorが使えると思う。有効期限の件もオプションで解決できるのではないか。

**Comment by poppen** [comment]
よさそうですね。

各サイトごとに共通のAPIを持たせてモジュール化もしておけば再利用も進みそうです。herokuからメール送信とか。

**Comment by tdtds** [comment]
thorizeブランチを作ってas isで移植してみました。ANAマイレージとか動作確認もできないので、ちょっと触ってみてもらえると助かります。

＃miscの下にzsh用compdefファイルを入れるという大サービスw

**Comment by poppen** [comment]
楽天、ANAマイレージともばっちりいけました！

**Comment by tdtds** [comment]
pull req #4 で取り込みました。また、0.1.0としてgemをリリースしました。
